### ISSUE TITLE
Support for custom OpenAI base path

### ISSUE THREAD

**Issue by bioshazard** [artificialcitizens/acai.so#49]
I am hosting a `llama-cpp-python[server]` instance on my localhost. I request that support be added to specify a custom base path like `http://localhost:8080`, eg:

![image](https://github.com/artificialcitizens/acai.so/assets/5616668/3ca69968-d604-4d63-a002-359d8a39da24)

I tried to get this working myself, but initial attempt seemed to be complicated by multiple places where the OpenAI instance is instantiated. Thanks!

**Comment by bioshazard** [comment]
I was actually able to get the chat working with my local service after adding a `baseURL` override in the `configuration` of the ChatOpenAI instantiation in chat-model.ts, will push later.

**Comment by bioshazard** [comment]
btw @mabry1985 idk about you but I feel like this is delivered

**Comment by mabry1985** [comment]
@bioshazard yup, thanks! Nice job here 🥇
