### ISSUE TITLE
Some Functionality Ideas

### ISSUE THREAD

**Issue by bioshazard** [artificialcitizens/acai.so#50]
Creating a single issue to capture all my ongoing thoughts while using this lovely software before opening a ton of separate issues. Planning to talk to Mabry before attempting any formal PRs to ensure my broad interests are each aligned with his vision so I don't waste cycles missing a good fit.

- Support Custom OpenAI Base URL: https://github.com/artificialcitizens/acai.so/issues/49 (imo `llama-cpp-python.server` is the future)
- For chat markdown render, consider [my GFM markdown render template for tailwind gist](https://gist.github.com/bioshazard/ce8c8d10eb16062825b06efdbfcc1c33)
- Sync (VectorDB, Config, Workspaces)
- [TwinGate](https://www.twingate.com/) setup guide (want to capture an attempt to make my local agent / endpoint accessible remotely)
- PWA + Share Target (and submit to https://store.app/)
- Remove splash page? (entrance to app is not 100% obvious imo, but idk, just reflecting)
- Add button to enable/disable passive microphone rather than by default (eg, "why am I being prompted for mic" might confuse?)
- Configure stop tokens
- Mobile responsiveness
- Full blown Obsidian alternative (or use it via [API](https://github.com/coddingtonbear/obsidian-local-rest-api)?) with plugins and everything
- Add websocket function to enable intermediate AI replies in chat prior to finalized execution (Mistral instruct fine-tune is incompatible with sequential AI messages, so we can transparently implode sequential messages for new message submissions)
- Seeing high CPU usage in idle tab on Brave (More Tools > Task Manager). Assuming there is some loop in the voice stuff idk yet haven't dug in.

Not obvious how a few of these ought function so I look forward to a discussion about them. Thanks for the hard work on ACAI.so! Hopeful I can contribute soon!

**Comment by mabry1985** [comment]
> Remove splash page? (entrance to app is not 100% obvious imo, but idk, just reflecting)

Yeah, its a bit intentional while the app is still in preview. I want to add a proper landing page for the beta release

I just merged a [PR](https://github.com/artificialcitizens/acai.so/pull/52) that added a link to the card in the middle to make navigation a bit more intuitive until then. This also adds functionality for tracking the current page and saving to local storage so that you can just use acai.so (or local base path) to get back to where you were.

Once we merge your model consolidation PR I want to add an override to this functionality so that you can choose what page you land on when visiting instead of the last used one.

**Comment by mabry1985** [comment]
> Seeing high CPU usage in idle tab on Brave (More Tools > Task Manager). Assuming there is some loop in the voice stuff idk yet haven't dug in.

I found it! It was the audio visualizer and it was always running even when not active. The speech recognition api is working fine from my tests, so thats great news. I'm pushing up a fix tonight

**Comment by bioshazard** [comment]
DOPE! also feel free to close this whenever, just a place I wanted to dump some thoughts. can open new issues accordingly.

**Comment by mabry1985** [comment]
mem leak fixed 🎉 https://github.com/artificialcitizens/acai.so/pull/53

**Comment by mabry1985** [comment]
I would love to see this, can you create an issue?

[TwinGate](https://www.twingate.com/) setup guide (want to capture an attempt to make my local agent / endpoint accessible remotely)

**Comment by mabry1985** [comment]
> Add button to enable/disable passive microphone rather than by default (eg, "why am I being prompted for mic" might confuse?)

This has been mostly addressed

**Comment by mabry1985** [comment]
I believe that the majority of this feedback has been implemented at this point. Closing the issue as resolved, feel free to open up any individual issues that remain

**Comment by bioshazard** [comment]
Wow, awesome 😎 great stuff!
